fn main()
	env.println("Dictionary construction:")
	var dict = {1: 2, 3: "dog", "cat": "chicken"}
	env.println("  ", dict)

	env.println("Setting dictionary index:")
	dict[1] = "duck"
	env.println("  ", dict)

	env.println("Iterating dictionaries:")
	for k in dict
		env.println("  ", k, ": ", dict[k])

	env.println("Using dictionary elements in expressions:")
	var sum = dict[3] + " is not a " + dict["cat"]
	env.println("  ", sum)
